name: Deploy
run-name: ${{ github.actor }} Deploy web site 🚀
on: [push, workflow_dispatch]
jobs:
  Deploy-VPS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/grabbit/current
            git checkout .
            git pull origin main 
            npm ci 
            npm run build 
            sudo caddy reload --config /etc/caddy/Caddyfile
