name: Deploy
run-name: ${{ github.actor }} Deploy web site 🚀
on: [push, workflow_dispatch]
jobs:
  Deploy-VPS:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/grabbit/current
            git checkout .
            git pull origin main 
            npm ci 
            npm run test
            npm run build 
            cd /var/www/grabbit/
            sudo caddy reload --config /etc/caddy/Caddyfile
